// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Mz5d5O5d3TBTAOuQ4Du0IG1H8C16kr8',
    appId: '1:694403477570:web:94856dd643e041287f7ddb',
    messagingSenderId: '694403477570',
    projectId: 'food-app-4ff6f',
    authDomain: 'food-app-4ff6f.firebaseapp.com',
    storageBucket: 'food-app-4ff6f.firebasestorage.app',
    measurementId: 'G-2F26QJ9PKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC528SNvGC3TFJNqB7EXlxm2Em0-LxVXm8',
    appId: '1:694403477570:android:4177ac2ecd958d5d7f7ddb',
    messagingSenderId: '694403477570',
    projectId: 'food-app-4ff6f',
    storageBucket: 'food-app-4ff6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxTxqb_GiQB5RSTbTnGgI2GUNyC8Q1uGo',
    appId: '1:694403477570:ios:f37a28af55d199267f7ddb',
    messagingSenderId: '694403477570',
    projectId: 'food-app-4ff6f',
    storageBucket: 'food-app-4ff6f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxTxqb_GiQB5RSTbTnGgI2GUNyC8Q1uGo',
    appId: '1:694403477570:ios:f37a28af55d199267f7ddb',
    messagingSenderId: '694403477570',
    projectId: 'food-app-4ff6f',
    storageBucket: 'food-app-4ff6f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Mz5d5O5d3TBTAOuQ4Du0IG1H8C16kr8',
    appId: '1:694403477570:web:cda022c37a94bace7f7ddb',
    messagingSenderId: '694403477570',
    projectId: 'food-app-4ff6f',
    authDomain: 'food-app-4ff6f.firebaseapp.com',
    storageBucket: 'food-app-4ff6f.firebasestorage.app',
    measurementId: 'G-XJ3V58SQGG',
  );
}
